### ISSUE TITLE
Bagnon ItemInfo causing FPS drops after opening bag

### ISSUE THREAD

**Issue by Nillx** [GoldpawsStuff/Bagnon_ItemInfo#7]
Noticed that every time i open my bag my FPS drops noticeable for a second when ItemInfo is enabled. Without it there are no issues.

**Comment by Nillx** [comment]
Installed the plugins individually and there are no issues, only having issues when i install ItemInfo. Pretty weird

**Comment by LudiusMaximus** [comment]
This is "normal" because the info of so many items has to be processed. If you activate my Plugin "Bagnon RequiredLevel" it gets even worse... Some day I will try to build a fix that distributes these calculations over as many frames as needed without reducing the frame rate. It should theoretically be possible if you keep checking the time with https://wow.gamepedia.com/API_debugprofilestop and when you have used up the time of the one frame, you stall whatever you are doing until the next OnUpdate. There also seem to be libraries for something like that: https://www.wowinterface.com/forums/showthread.php?p=336268#post336268

**Comment by goldpaw** [comment]
Never looked much into this, but have added some safeguards in the very latest update against potential pitfalls that might have been happening, where some textures would be created multiple times. That could've caused a fps drop if you had plenty of items in the bags.
